### ISSUE TITLE
Option to toggle changes to other Trinkets

### ISSUE THREAD

**Issue by Ski-z** [fonnymunkey/RLArtifacts#1]
Could we get a toggle for removing the other trinkets?

 I want to use your mod, but not Bountiful Baubles. I would love the rendering features (especially MoBends compat) and adjustments of your mod with these baubles, without having to install BB just to get the obsidian skull.

It looks way cooler in this mod anyway!

**Comment by fonnymunkey** [comment]
1.1.0 is currently uploaded and processing, it adds a config option to re-enable legacy items that overlap with BountifulBaubles such as the Obsidian Skull and Lucky Horseshoe, and should make those models work with MoBends as well.

The only thing is that they do not drop from the Mimic loot table since they are disabled by default, they will need to be added to it with LootTweaker or obtained through another method if you want to use the legacy items.
