### ISSUE TITLE
If Mimic spawned instead Lootr chest, it will still be here (bugged and unusable)

### ISSUE THREAD

**Issue by ghost** [fonnymunkey/RLArtifacts#2]
![Untitled](https://github.com/fonnymunkey/RLArtifacts/assets/45370592/b7b9b758-b4f2-42c3-9f68-37cee70fa360)

**Comment by fonnymunkey** [comment]
Mimic spawning from unlooted chests inherently does not work with how Lootr changes chests.
If you want to use the two mods together, in the config set "Unlooted Chest Mimic Chance" to 0.0, and then set "Underground Chest Chance" and "Underground Chest Mimic Chance" to higher values to have Mimics directly spawn underground randomly like chests.

**Comment by ghost** [comment]
It was underground one created by Apotheosis mod

**Comment by fonnymunkey** [comment]
That doesn't change what I said, Mimics spawning from chests regardless of what makes the chest won't work with Lootr, it inherently doesn't work with what Lootr is designed to do and I have no plans of trying to change that.
If you want Mimics to work with Lootr, do the config changes I posted which will make Mimics directly spawn underground instead of from chests, which will avoid this issue.
